version: "3.9"
name: sga
services:
  load-balancer:
    image: nginx:1.27.0-alpine
    container_name: load-balancer
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/ssl.crt:/etc/nginx/ssl/ssl.crt:ro
      - ./config/ssl.key:/etc/nginx/ssl/ssl.key:ro
    networks:
      - sga

  sga-database:
    image: postgres:16.0-alpine3.18
    container_name: sga-database
    environment:
      - POSTGRES_USER=sga
      - POSTGRES_PASSWORD=Temp1234
      - PGDATA=/var/lib/postgresql-static/data
    volumes:
      - sga-db:/var/lib/postgresql-static/data
    ports:
      - "5432:5432"
    networks:
      - sga

networks:
  sga:

volumes:
  sga-db:
    driver: local
